apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: redis-app-rc
   labels:
     name: redis-app-rc
     app: demo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app-rc
  template:
    metadata:
      name: redis-app-rc
      labels:
        name: redis-app-rc
        app: demo-test
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
