apiVersion: v1
kind: Service
metadata:
  name: redis-srv
  labels:
    name: redis-srv     
    app: demo-test
spec:
  type: ClusterIP      
  selector:
    name: redis-app-rc
    app: demo-test       
  ports:
    - port: 6379
      targetPort: 6379
  
