apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: result-rc
   labels: 
     name: result-rc
     app: demo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-rc
  template:
    metadata:
      name: result-app-rc
      labels: 
        name: result-app-rc
        app: demo-test
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
   


