apiVersion: v1
kind: Service
metadata:
  name: result-srv
  labels:
    name: result-srv     
    app: demo-test
spec:
  selector:
    name: result-app-rc
    app: demo-test       
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  
