apiVersion: v1
kind: Service
metadata:
  name: voting-srv
  labels:
    name: voting-srv     
    app: demo-test
spec:
  selector:
    name: voting-app-rc
    app: demo-test       
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  
